#!/usr/bin/env python3
"""Replay an existing operating-characteristics bundle through native Python MML.

The generator is intentionally out of scope: this adapter consumes byte-retained
ratings, truth, and anchors produced by ``operating_characteristics.py``.  Its
purpose is to put the application's own marginal-likelihood estimator on the
same run ledger as FACETS JMLE, TAM/sirt MML, and exact CMLE.

The two registered pilot modes separate a correct fixed population-SD analysis
from free population-SD estimation.  They are operating-characteristic
comparisons, not direct FACETS-equality tests: FACETS 4.5 uses JMLE.
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
import time
import warnings
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from validation.operating_characteristics_facets import (  # noqa: E402
    RECOVERY_FACETS,
    align_recovery,
    sha256_file,
    validate_bundle,
)


SCHEMA_VERSION = "mfrm-python-mml-oc-adapter-v1"
MODE_SPECS: dict[str, dict[str, Any]] = {
    "PYTHON_MML_FIXED_SD1_Q31": {
        "quad_points": 31,
        "estimate_population_sd": False,
        "population_prior_sd": 1.0,
        "role": "registered_fixed_generator_sd_pilot",
    },
    "PYTHON_MML_FREE_SD_Q31": {
        "quad_points": 31,
        "estimate_population_sd": True,
        "population_prior_sd": 1.0,
        "role": "registered_free_population_sd_pilot",
    },
    "PYTHON_MML_FIXED_SD1_Q61": {
        "quad_points": 61,
        "estimate_population_sd": False,
        "population_prior_sd": 1.0,
        "role": "quadrature_sensitivity",
    },
    "PYTHON_MML_FREE_SD_Q61": {
        "quad_points": 61,
        "estimate_population_sd": True,
        "population_prior_sd": 1.0,
        "role": "quadrature_sensitivity",
    },
}
DEFAULT_MODES = ("PYTHON_MML_FIXED_SD1_Q31", "PYTHON_MML_FREE_SD_Q31")
OUTPUT_FILES = (
    "python_mml_runs.csv",
    "python_mml_parameter_recovery.csv",
    "python_mml_person_estimates.csv",
    "python_mml_fit_metrics.csv",
    "python_mml_adapter_identity.json",
)


def _number(value: Any) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return float("nan")
    return numeric if np.isfinite(numeric) else float("nan")


def _git_identity(repo: Path) -> dict[str, str]:
    def run(*args: str) -> str:
        return subprocess.check_output(args, cwd=repo, text=True).strip()

    try:
        return {
            "git_head": run("git", "rev-parse", "HEAD"),
            "git_branch": run("git", "branch", "--show-current"),
            "git_status": run("git", "status", "--short"),
        }
    except Exception as exc:  # pragma: no cover - provenance fallback
        return {"git_error": f"{type(exc).__name__}: {exc}"}


def validate_registered_bundle_hashes(input_dir: Path) -> dict[str, str]:
    """Verify generated byte identity when the generator ledger is present."""

    ledger_path = input_dir / "generated_bundle_files.csv"
    if not ledger_path.is_file():
        return {}
    ledger = pd.read_csv(ledger_path)
    required = {"File", "SHA256"}
    missing = required.difference(ledger.columns)
    if missing:
        raise ValueError(f"generated_bundle_files.csv is missing columns: {sorted(missing)}")
    observed: dict[str, str] = {}
    for row in ledger.itertuples(index=False):
        path = input_dir / str(row.File)
        if not path.is_file():
            raise FileNotFoundError(f"Registered generated bundle file is missing: {path}")
        digest = sha256_file(path)
        expected = str(row.SHA256).lower()
        if digest.lower() != expected:
            raise ValueError(
                f"Registered SHA256 mismatch for {path.name}: expected {expected}, got {digest}"
            )
        observed[path.name] = digest
    return observed


def build_mml_kwargs(mode: str, categories: int) -> dict[str, Any]:
    if mode not in MODE_SPECS:
        raise ValueError(f"Unknown native MML mode: {mode}")
    spec = MODE_SPECS[mode]
    return {
        "person_col": "Person",
        "facet_cols": ["Rater", "Task", "Criterion"],
        "score_col": "Score",
        "rating_min": 0,
        "rating_max": int(categories) - 1,
        "model": "RSM",
        "method": "MML",
        # The latent population mean identifies Person location under MML.  One
        # observed facet must carry the additive location otherwise absorbed by
        # JMLE's noncentered Person facet.
        "noncenter_facet": "Criterion",
        "mml_engine": "EM",
        "quad_points": int(spec["quad_points"]),
        "estimate_population_sd": bool(spec["estimate_population_sd"]),
        "population_prior_sd": float(spec["population_prior_sd"]),
        "maxit": 350,
        "reltol": 1e-7,
        "anchor_policy": "warn",
        "min_common_anchors": 2,
        "min_obs_per_element": 1,
        "min_obs_per_category": 1,
        "keep_original": True,
    }


def normalize_mml_recovery(
    measures: pd.DataFrame,
    truth: pd.DataFrame,
    anchors: pd.DataFrame,
    manifest_row: pd.Series,
    *,
    mode: str,
    eligible: bool,
    structurally_identified: bool | None,
) -> pd.DataFrame:
    estimates = measures.loc[
        measures["Facet"].astype(str).isin(RECOVERY_FACETS),
        [column for column in ("Facet", "Level", "Estimate", "SE", "Status") if column in measures],
    ].copy()
    if "SE" not in estimates:
        estimates["SE"] = np.nan
    if "Status" not in estimates:
        estimates["Status"] = np.nan
    recovery = align_recovery(estimates, truth, anchors, manifest_row)
    recovery["Engine"] = "PythonApp"
    recovery["Estimator"] = "MML"
    recovery["Mode"] = mode
    recovery["ComparisonClass"] = "native_marginal_sensitivity"
    recovery["MMLIdentificationBasis"] = "normal_population_distribution"
    recovery["ObservedDesignStructurallyIdentified"] = structurally_identified
    recovery["IncludedInSummary"] &= bool(eligible)
    recovery["CoverageMethod"] = (
        "native MML observed-information/delta-method diagnostic; "
        "mean-aligned unless anchor-identified"
    )
    return recovery


def _structural_ledger(input_dir: Path, explicit_path: Path | None) -> tuple[pd.DataFrame, str]:
    path = explicit_path
    if path is None:
        candidate = (
            input_dir.parent
            / "operating_characteristics_identifiability_20260809"
            / "jmle_identifiability_runs.csv"
        )
        path = candidate if candidate.is_file() else None
    if path is None:
        return pd.DataFrame(), "unavailable"
    path = path.resolve()
    ledger = pd.read_csv(path)
    required = {"RunId", "StructurallyIdentified", "StructuralNullity"}
    missing = required.difference(ledger.columns)
    if missing:
        raise ValueError(f"Identifiability ledger is missing columns: {sorted(missing)}")
    ledger["RunId"] = ledger["RunId"].astype(str)
    return ledger.drop_duplicates("RunId").set_index("RunId"), str(path)


def _structural_values(ledger: pd.DataFrame, run_id: str) -> tuple[bool | None, float]:
    if ledger.empty or run_id not in ledger.index:
        return None, float("nan")
    row = ledger.loc[run_id]
    identified = str(row["StructurallyIdentified"]).strip().lower() == "true"
    return identified, _number(row["StructuralNullity"])


def _person_output(result: dict[str, Any], manifest_row: pd.Series, mode: str) -> pd.DataFrame:
    table = result["facets"]["person"].copy()
    output = pd.DataFrame({
        "RunId": manifest_row["RunId"],
        "ConditionId": manifest_row["ConditionId"],
        "Design": manifest_row["Design"],
        "TruthBias": manifest_row["TruthBias"],
        "Replicate": manifest_row["Replicate"],
        "Seed": manifest_row["Seed"],
        "Engine": "PythonApp",
        "Estimator": "MML",
        "Mode": mode,
        "Person": table["Person"].astype(str),
        "Estimate": pd.to_numeric(table["Estimate"], errors="coerce"),
    })
    for column in ("SD", "SE", "CI_Lower", "CI_Upper"):
        if column in table:
            output[column] = pd.to_numeric(table[column], errors="coerce")
    return output


def _fit_output(diagnostics: dict[str, Any], manifest_row: pd.Series, mode: str) -> pd.DataFrame:
    table = diagnostics.get("measures", pd.DataFrame()).copy()
    if table.empty:
        return pd.DataFrame()
    keep = [
        column for column in (
            "Facet", "Level", "N_Fit", "Infit", "Outfit", "Infit_ZSTD", "Outfit_ZSTD",
            "PtMeasureCorr", "ExpectedPtMeasureCorr",
        ) if column in table
    ]
    output = table[keep].copy()
    output.insert(0, "Mode", mode)
    output.insert(0, "Estimator", "MML")
    output.insert(0, "Engine", "PythonApp")
    output.insert(0, "RunId", manifest_row["RunId"])
    output["MetricPrecision"] = "native_full_precision"
    output["FACETSComparability"] = (
        "not_direct: FACETS 4.5 displayed fit is rounded to 2 decimals and uses JMLE"
    )
    return output


def fit_one(
    app: Any,
    manifest_row: pd.Series,
    ratings: pd.DataFrame,
    truth: pd.DataFrame,
    anchors: pd.DataFrame,
    *,
    mode: str,
    structurally_identified: bool | None,
    structural_nullity: float,
) -> tuple[dict[str, Any], pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    started = time.perf_counter()
    warning_messages: list[str] = []
    base = {column: manifest_row[column] for column in manifest_row.index}
    spec = MODE_SPECS[mode]
    run: dict[str, Any] = {
        **base,
        "Engine": "PythonApp",
        "Estimator": "MML",
        "Mode": mode,
        "ModeRole": spec["role"],
        "QuadraturePoints": spec["quad_points"],
        "PopulationSDMode": "estimated" if spec["estimate_population_sd"] else "fixed",
        "PopulationSDInput": spec["population_prior_sd"],
        "EstimatedPopulationSD": np.nan,
        "PopulationSDSE": np.nan,
        "FitReturned": False,
        "Converged": False,
        "AnalysisEligible": False,
        "FailureReason": "",
        "Warnings": "",
        "Rows": int(len(ratings)),
        "ObservedDesignStructurallyIdentified": structurally_identified,
        "ObservedDesignStructuralNullity": structural_nullity,
        "MMLIdentificationBasis": "normal_population_distribution",
        "ComparisonClass": "native_marginal_sensitivity",
        "ElapsedSeconds": np.nan,
    }
    try:
        kwargs = build_mml_kwargs(mode, int(manifest_row["Categories"]))
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            result = app.mfrm_estimate(
                data=ratings[["Person", "Rater", "Task", "Criterion", "Score"]].copy(),
                anchor_df=anchors[["Facet", "Level", "Anchor"]].copy() if not anchors.empty else None,
                **kwargs,
            )
            diagnostics = app.mfrm_diagnostics(
                result,
                compute_pca=False,
                compute_marginal=False,
                compute_eb_shrinkage=False,
            )
            warning_messages = [str(item.message) for item in caught]
        summary = result["summary"].iloc[0]
        config = result["config"]
        converged = bool(summary.get("Converged", False))
        measures = diagnostics.get("measures", pd.DataFrame())
        expected_keys = set(map(tuple, truth[["Facet", "Level"]].astype(str).to_numpy()))
        observed_keys = set(map(tuple, measures[["Facet", "Level"]].astype(str).to_numpy()))
        finite_main = measures.loc[
            measures["Facet"].astype(str).isin(RECOVERY_FACETS), "Estimate"
        ].apply(pd.to_numeric, errors="coerce").notna().all()
        eligible = bool(converged and expected_keys.issubset(observed_keys) and finite_main)
        run.update({
            "FitReturned": True,
            "Converged": converged,
            "AnalysisEligible": eligible,
            "EstimatedPopulationSD": _number(config.get("estimated_population_sd")),
            "PopulationSDSE": _number(config.get("population_sd_se")),
            "LogLik": _number(summary.get("LogLik")),
            "KParams": _number(summary.get("KParams")),
            "Iterations": _number(summary.get("Iterations")),
            "GradientNorm": _number(summary.get("GradientNorm")),
            "MMLResolvedEngine": str(config.get("mml_engine", "")),
            "InferenceReady": bool(summary.get("InferenceReady", False)),
        })
        recovery = normalize_mml_recovery(
            measures,
            truth,
            anchors,
            manifest_row,
            mode=mode,
            eligible=eligible,
            structurally_identified=structurally_identified,
        )
        return run, recovery, _person_output(result, manifest_row, mode), _fit_output(diagnostics, manifest_row, mode)
    except Exception as exc:  # complete attempt ledger, including diagnostic failures
        run["FailureReason"] = f"{type(exc).__name__}: {exc}"
        return run, pd.DataFrame(), pd.DataFrame(), pd.DataFrame()
    finally:
        run["Warnings"] = " | ".join(warning_messages)
        run["ElapsedSeconds"] = time.perf_counter() - started


def run_adapter(args: argparse.Namespace) -> None:
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()
    tables = validate_bundle(input_dir)
    registered_hashes = validate_registered_bundle_hashes(input_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    existing = [output_dir / name for name in OUTPUT_FILES if (output_dir / name).exists()]
    if existing and not args.overwrite:
        raise FileExistsError(
            "Native MML output already exists; pass --overwrite to replace only these files: "
            + ", ".join(path.name for path in existing)
        )

    modes = tuple(args.mode or DEFAULT_MODES)
    unknown_modes = set(modes).difference(MODE_SPECS)
    if unknown_modes:
        raise ValueError(f"Unknown --mode values: {sorted(unknown_modes)}")

    manifest = tables["manifest.csv"].copy()
    if args.run_id:
        requested = set(args.run_id)
        manifest = manifest[manifest["RunId"].astype(str).isin(requested)]
        missing = requested.difference(manifest["RunId"].astype(str))
        if missing:
            raise ValueError(f"Requested RunIds are absent from manifest: {sorted(missing)}")
    if args.limit is not None:
        manifest = manifest.head(args.limit)
    if manifest.empty:
        raise ValueError("No manifest rows selected")

    ledger, ledger_source = _structural_ledger(input_dir, args.identifiability_runs)
    import streamlit_app as app  # pylint: disable=import-outside-toplevel

    ratings_all = tables["generated_ratings.csv"]
    truth_all = tables["generated_facet_truth.csv"]
    anchors_all = tables["generated_anchors.csv"]
    runs: list[dict[str, Any]] = []
    recovery_parts: list[pd.DataFrame] = []
    person_parts: list[pd.DataFrame] = []
    fit_parts: list[pd.DataFrame] = []
    attempts = len(manifest) * len(modes)
    for _, manifest_row in manifest.iterrows():
        run_id = str(manifest_row["RunId"])
        ratings = ratings_all[ratings_all["RunId"].astype(str).eq(run_id)].copy()
        truth = truth_all[truth_all["RunId"].astype(str).eq(run_id)].copy()
        anchors = anchors_all[anchors_all["RunId"].astype(str).eq(run_id)].copy()
        identified, nullity = _structural_values(ledger, run_id)
        for mode in modes:
            run, recovery, persons, fit = fit_one(
                app,
                manifest_row,
                ratings,
                truth,
                anchors,
                mode=mode,
                structurally_identified=identified,
                structural_nullity=nullity,
            )
            runs.append(run)
            if not recovery.empty:
                recovery_parts.append(recovery)
            if not persons.empty:
                person_parts.append(persons)
            if not fit.empty:
                fit_parts.append(fit)
            print(
                f"[{len(runs):03d}/{attempts:03d}] {run_id} {mode}: "
                f"returned={run['FitReturned']} converged={run['Converged']} "
                f"eligible={run['AnalysisEligible']}",
                flush=True,
            )

    pd.DataFrame(runs).to_csv(output_dir / "python_mml_runs.csv", index=False)
    (pd.concat(recovery_parts, ignore_index=True) if recovery_parts else pd.DataFrame()).to_csv(
        output_dir / "python_mml_parameter_recovery.csv", index=False
    )
    (pd.concat(person_parts, ignore_index=True) if person_parts else pd.DataFrame()).to_csv(
        output_dir / "python_mml_person_estimates.csv", index=False
    )
    (pd.concat(fit_parts, ignore_index=True) if fit_parts else pd.DataFrame()).to_csv(
        output_dir / "python_mml_fit_metrics.csv", index=False
    )

    identity = {
        "schema_version": SCHEMA_VERSION,
        "adapter_sha256": sha256_file(Path(__file__).resolve()),
        "app_file": str((REPO_ROOT / "streamlit_app.py").resolve()),
        "app_sha256": sha256_file(REPO_ROOT / "streamlit_app.py"),
        "python_version": sys.version,
        "platform": platform.platform(),
        "selected_runs": int(len(manifest)),
        "selected_modes": list(modes),
        "mode_specs": {mode: MODE_SPECS[mode] for mode in modes},
        "identifiability_ledger": ledger_source,
        "registered_generated_file_sha256": registered_hashes,
        "interpretation_contract": {
            "estimand": "marginal likelihood with a normal Person population",
            "facets_role": "operating-characteristic sensitivity; not FACETS equality",
            "sparse_design_role": (
                "assumption-based marginal identification; JMLE structural-nullity ledger is annotation, not exclusion"
            ),
            "fit_precision": (
                "native Python full precision retained; FACETS 4.5 fit text is only displayed to two decimals"
            ),
        },
        **_git_identity(REPO_ROOT),
    }
    (output_dir / "python_mml_adapter_identity.json").write_text(
        json.dumps(identity, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--mode", action="append", choices=tuple(MODE_SPECS))
    parser.add_argument("--run-id", action="append", help="Repeat to select exact RunIds")
    parser.add_argument("--limit", type=int)
    parser.add_argument("--identifiability-runs", type=Path)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args(argv)


def main() -> None:
    run_adapter(parse_args())


if __name__ == "__main__":
    main()
